[package]
name = "deathblows/server-browser"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Vide = "centau/vide@0.3.1"
GreenTea = "corecii/greentea@0.4.11"
LucideIcons = "latte-soft/lucide-icons@0.1.3"
Replica = "azutreo/replica@1.0.1"
Lyra = "paradoxum-games/lyra@0.6.0"
Loader = "sleitnick/loader@2.0.0"
Signal = "sleitnick/signal@2.0.3"
Component = "sleitnick/component@2.4.8"
VideCharm = "littensy/vide-charm@0.3.0"
Charm = "littensy/charm@^0.10"
Trove = "sleitnick/trove@1.8.0"
Promise = "maximumadhd/promise-typed@1.0.0"
Sift = "csqrl/sift@0.0.11"
Conch = "alicesaidhi/conch@0.3.1"
ConchUI = "alicesaidhi/conch-ui@0.3.1"
FastCast = "megamonsta2/fastcast@1.0.0"
Iris = "sirmallard/iris@2.5.0"
Remo = "littensy/remo@1.5.3"

[server-dependencies]
